package objects

import (
	"fmt"
	"encoding/binary"
	"github.com/miekg/pkcs11"
)

// AttrToString converts a single *pkcs11.Attribute to a human-readable string like "CKA_CLASS: CKO_PUBLIC_KEY".
// Handles common types; falls back to hex for unknowns.
func AttrToString(attr *pkcs11.Attribute) string {
    typeName := getAttrName(attr.Type)
    var valStr string

    switch attr.Type {
    // Enums: Object classes
    case pkcs11.CKA_CLASS:
        if len(attr.Value) == 8 {
			class := binary.LittleEndian.Uint32(attr.Value[:4])
            valStr = getObjectClassName(class)
        }

    // Enums: Key types
    case pkcs11.CKA_KEY_TYPE:
        if len(attr.Value) == 8 {
			keyType := binary.LittleEndian.Uint32(attr.Value[:4])
            valStr = getKeyTypeName(keyType)
        }

    // Enums: Certificate types (for CKA_CERTIFICATE_TYPE)
    case pkcs11.CKA_CERTIFICATE_TYPE:
        if len(attr.Value) == 8 {
            certType := binary.LittleEndian.Uint32(attr.Value[:4])
            switch certType {
            case 0x00000000: valStr = "CKC_X_509"
            case 0x00000001: valStr = "CKC_X_509_ATTR_CERT"
            case 0x00000002: valStr = "CKC_WTLS"
            case 0x00000003: valStr = "CKC_VENDOR_DEFINED"
            default: valStr = fmt.Sprintf("CKC_UNKNOWN(0x%08x)", certType)
            }
        }

    // Mechanism types (e.g., for CKA_KEY_GEN_MECHANISM)
    case pkcs11.CKA_KEY_GEN_MECHANISM:
        if len(attr.Value) == 8 {
            mech := binary.LittleEndian.Uint32(attr.Value[:4])
            valStr = getMechanismName(mech)
        }

    // Booleans (single byte: 0x00=false, 0xFF=true)
    case pkcs11.CKA_TOKEN, pkcs11.CKA_PRIVATE, pkcs11.CKA_SENSITIVE,
         pkcs11.CKA_ENCRYPT, pkcs11.CKA_DECRYPT, pkcs11.CKA_WRAP,
         pkcs11.CKA_UNWRAP, pkcs11.CKA_SIGN, pkcs11.CKA_SIGN_RECOVER,
         pkcs11.CKA_VERIFY, pkcs11.CKA_VERIFY_RECOVER, pkcs11.CKA_DERIVE,
         pkcs11.CKA_EXTRACTABLE, pkcs11.CKA_LOCAL, pkcs11.CKA_NEVER_EXTRACTABLE,
         pkcs11.CKA_ALWAYS_SENSITIVE, pkcs11.CKA_MODIFIABLE, pkcs11.CKA_COPYABLE,
         pkcs11.CKA_DESTROYABLE, pkcs11.CKA_ALWAYS_AUTHENTICATE, pkcs11.CKA_TRUSTED:
        valStr = "false"
        if len(attr.Value) == 1 && attr.Value[0] == 0xFF {
            valStr = "true"
        }

    // Strings
    case pkcs11.CKA_LABEL, pkcs11.CKA_APPLICATION, pkcs11.CKA_SUBJECT,
         pkcs11.CKA_ISSUER, pkcs11.CKA_SERIAL_NUMBER, pkcs11.CKA_URL:
        valStr = fmt.Sprintf("%q", string(attr.Value)) // Quoted for readability

    // Dates (8-byte YYYYMMDDhhmmss00, but simplified to string)
    case pkcs11.CKA_START_DATE, pkcs11.CKA_END_DATE:
        if len(attr.Value) == 16 { // Often padded
            valStr = string(attr.Value[:8]) // YYYYMMDDhhmmss00 -> YYYY-MM-DD hh:mm:ss (manual format if needed)
        } else {
            valStr = string(attr.Value)
        }

    // Small integers (uint32)
    case pkcs11.CKA_MODULUS_BITS, pkcs11.CKA_PRIME_BITS, pkcs11.CKA_SUBPRIME_BITS,
         pkcs11.CKA_VALUE_BITS, pkcs11.CKA_VALUE_LEN:
        if len(attr.Value) == 8 {
            num := binary.LittleEndian.Uint32(attr.Value[:4])
            valStr = fmt.Sprintf("%d", num)
        }

    // Binary data (hex dump)
    case pkcs11.CKA_VALUE, pkcs11.CKA_ID, pkcs11.CKA_MODULUS,
         pkcs11.CKA_PUBLIC_EXPONENT, pkcs11.CKA_PRIVATE_EXPONENT,
         pkcs11.CKA_PRIME_1, pkcs11.CKA_PRIME_2, pkcs11.CKA_EXPONENT_1,
         pkcs11.CKA_EXPONENT_2, pkcs11.CKA_COEFFICIENT, pkcs11.CKA_PRIME,
         pkcs11.CKA_SUBPRIME, pkcs11.CKA_BASE, pkcs11.CKA_EC_PARAMS,
         pkcs11.CKA_EC_POINT, pkcs11.CKA_PUBLIC_KEY_INFO, pkcs11.CKA_CHECK_VALUE:
        valStr = fmt.Sprintf("0x%x", attr.Value) // Compact hex

    // Other arrays (e.g., CKA_WRAP_TEMPLATE) - treat as hex
    case pkcs11.CKA_WRAP_TEMPLATE, pkcs11.CKA_UNWRAP_TEMPLATE,
         pkcs11.CKA_ATTR_TYPES:
        valStr = fmt.Sprintf("0x%x", attr.Value)

    // Fallback for unknowns
    default:
        valStr = fmt.Sprintf("0x%x", attr.Value)
    }

    return fmt.Sprintf("%s: %s", typeName, valStr)
}

// getAttrName returns the string name for an attribute type.
func getAttrName(t uint) string {
    attrNames := map[uint]string{
        // Core attributes
        pkcs11.CKA_CLASS:                "CKA_CLASS",
        pkcs11.CKA_TOKEN:                "CKA_TOKEN",
        pkcs11.CKA_PRIVATE:              "CKA_PRIVATE",
        pkcs11.CKA_LABEL:                "CKA_LABEL",
        pkcs11.CKA_APPLICATION:          "CKA_APPLICATION",
        pkcs11.CKA_VALUE:                "CKA_VALUE",
        pkcs11.CKA_OBJECT_ID:            "CKA_OBJECT_ID",
        pkcs11.CKA_CERTIFICATE_TYPE:     "CKA_CERTIFICATE_TYPE",
        pkcs11.CKA_ISSUER:               "CKA_ISSUER",
        pkcs11.CKA_SERIAL_NUMBER:        "CKA_SERIAL_NUMBER",
        pkcs11.CKA_AC_ISSUER:            "CKA_AC_ISSUER",
        pkcs11.CKA_OWNER:                "CKA_OWNER",
        pkcs11.CKA_ATTR_TYPES:           "CKA_ATTR_TYPES",
        pkcs11.CKA_TRUSTED:              "CKA_TRUSTED",
        pkcs11.CKA_CERTIFICATE_CATEGORY: "CKA_CERTIFICATE_CATEGORY",
        pkcs11.CKA_JAVA_MIDP_SECURITY_DOMAIN: "CKA_JAVA_MIDP_SECURITY_DOMAIN",
        pkcs11.CKA_URL:                  "CKA_URL",
        pkcs11.CKA_HASH_OF_SUBJECT_PUBLIC_KEY: "CKA_HASH_OF_SUBJECT_PUBLIC_KEY",
        pkcs11.CKA_HASH_OF_ISSUER_PUBLIC_KEY:  "CKA_HASH_OF_ISSUER_PUBLIC_KEY",
        pkcs11.CKA_CHECK_VALUE:          "CKA_CHECK_VALUE",

        // Key attributes
        pkcs11.CKA_KEY_TYPE:             "CKA_KEY_TYPE",
        pkcs11.CKA_SUBJECT:              "CKA_SUBJECT",
        pkcs11.CKA_ID:                   "CKA_ID",
        pkcs11.CKA_SENSITIVE:            "CKA_SENSITIVE",
        pkcs11.CKA_ENCRYPT:              "CKA_ENCRYPT",
        pkcs11.CKA_DECRYPT:              "CKA_DECRYPT",
        pkcs11.CKA_WRAP:                 "CKA_WRAP",
        pkcs11.CKA_UNWRAP:               "CKA_UNWRAP",
        pkcs11.CKA_SIGN:                 "CKA_SIGN",
        pkcs11.CKA_SIGN_RECOVER:         "CKA_SIGN_RECOVER",
        pkcs11.CKA_VERIFY:               "CKA_VERIFY",
        pkcs11.CKA_VERIFY_RECOVER:       "CKA_VERIFY_RECOVER",
        pkcs11.CKA_DERIVE:               "CKA_DERIVE",
        pkcs11.CKA_START_DATE:           "CKA_START_DATE",
        pkcs11.CKA_END_DATE:             "CKA_END_DATE",
        pkcs11.CKA_MODULUS:              "CKA_MODULUS",
        pkcs11.CKA_MODULUS_BITS:         "CKA_MODULUS_BITS",
        pkcs11.CKA_PUBLIC_EXPONENT:      "CKA_PUBLIC_EXPONENT",
        pkcs11.CKA_PRIVATE_EXPONENT:     "CKA_PRIVATE_EXPONENT",
        pkcs11.CKA_PRIME_1:              "CKA_PRIME_1",
        pkcs11.CKA_PRIME_2:              "CKA_PRIME_2",
        pkcs11.CKA_EXPONENT_1:           "CKA_EXPONENT_1",
        pkcs11.CKA_EXPONENT_2:           "CKA_EXPONENT_2",
        pkcs11.CKA_COEFFICIENT:          "CKA_COEFFICIENT",
        pkcs11.CKA_PUBLIC_KEY_INFO:      "CKA_PUBLIC_KEY_INFO",
        pkcs11.CKA_PRIME:                "CKA_PRIME",
        pkcs11.CKA_SUBPRIME:             "CKA_SUBPRIME",
        pkcs11.CKA_BASE:                 "CKA_BASE",
        pkcs11.CKA_PRIME_BITS:           "CKA_PRIME_BITS",
        pkcs11.CKA_SUBPRIME_BITS:        "CKA_SUBPRIME_BITS",
        pkcs11.CKA_VALUE_BITS:           "CKA_VALUE_BITS",
        pkcs11.CKA_VALUE_LEN:            "CKA_VALUE_LEN",
        pkcs11.CKA_EXTRACTABLE:          "CKA_EXTRACTABLE",
        pkcs11.CKA_LOCAL:                "CKA_LOCAL",
        pkcs11.CKA_NEVER_EXTRACTABLE:    "CKA_NEVER_EXTRACTABLE",
        pkcs11.CKA_ALWAYS_SENSITIVE:     "CKA_ALWAYS_SENSITIVE",
        pkcs11.CKA_KEY_GEN_MECHANISM:    "CKA_KEY_GEN_MECHANISM",
        pkcs11.CKA_MODIFIABLE:           "CKA_MODIFIABLE",
        pkcs11.CKA_COPYABLE:             "CKA_COPYABLE",
        pkcs11.CKA_DESTROYABLE:          "CKA_DESTROYABLE",
        pkcs11.CKA_EC_PARAMS:            "CKA_EC_PARAMS",
        pkcs11.CKA_EC_POINT:             "CKA_EC_POINT",
        pkcs11.CKA_ALWAYS_AUTHENTICATE:  "CKA_ALWAYS_AUTHENTICATE",
        pkcs11.CKA_WRAP_WITH_TRUSTED:    "CKA_WRAP_WITH_TRUSTED",
        pkcs11.CKA_WRAP_TEMPLATE:        "CKA_WRAP_TEMPLATE",
        pkcs11.CKA_UNWRAP_TEMPLATE:      "CKA_UNWRAP_TEMPLATE",
    }
    if name, ok := attrNames[t]; ok {
        return name
    }
    return fmt.Sprintf("CKA_UNKNOWN(0x%08x)", t)
}

// getObjectClassName maps CKO_ values to strings.
func getObjectClassName(class uint32) string {
    switch class {
    case pkcs11.CKO_DATA: return "CKO_DATA"
    case pkcs11.CKO_CERTIFICATE: return "CKO_CERTIFICATE"
    case pkcs11.CKO_PUBLIC_KEY: return "CKO_PUBLIC_KEY"
    case pkcs11.CKO_PRIVATE_KEY: return "CKO_PRIVATE_KEY"
    case pkcs11.CKO_SECRET_KEY: return "CKO_SECRET_KEY"
    case pkcs11.CKO_HW_FEATURE: return "CKO_HW_FEATURE"
    case pkcs11.CKO_DOMAIN_PARAMETERS: return "CKO_DOMAIN_PARAMETERS"
    case pkcs11.CKO_MECHANISM: return "CKO_MECHANISM"
    case pkcs11.CKO_OTP_KEY: return "CKO_OTP_KEY"
    case 0x80000000: return "CKO_VENDOR_DEFINED"
    default: return fmt.Sprintf("CKO_UNKNOWN(0x%08x)", class)
    }
}

// getKeyTypeName maps CKK_ values to strings.
func getKeyTypeName(keyType uint32) string {
    switch keyType {
    case pkcs11.CKK_RSA: return "CKK_RSA"
    case pkcs11.CKK_DSA: return "CKK_DSA"
    case pkcs11.CKK_DH: return "CKK_DH"
    case pkcs11.CKK_EC: return "CKK_ECDSA"
    case pkcs11.CKK_X9_42_DH: return "CKK_X9_42_DH"
    case pkcs11.CKK_KEA: return "CKK_KEA"
    case pkcs11.CKK_GENERIC_SECRET: return "CKK_GENERIC_SECRET"
    case pkcs11.CKK_RC2: return "CKK_RC2"
    case pkcs11.CKK_RC4: return "CKK_RC4"
    case pkcs11.CKK_DES: return "CKK_DES"
    case pkcs11.CKK_DES2: return "CKK_DES2"
    case pkcs11.CKK_DES3: return "CKK_DES3"
    case pkcs11.CKK_CAST: return "CKK_CAST"
    case pkcs11.CKK_CAST3: return "CKK_CAST3"
    case pkcs11.CKK_CAST128: return "CKK_CAST128"
    case pkcs11.CKK_RC5: return "CKK_RC5"
    case pkcs11.CKK_IDEA: return "CKK_IDEA"
    case pkcs11.CKK_SKIPJACK: return "CKK_SKIPJACK"
    case pkcs11.CKK_BATON: return "CKK_BATON"
    case pkcs11.CKK_JUNIPER: return "CKK_JUNIPER"
    case pkcs11.CKK_CDMF: return "CKK_CDMF"
    case pkcs11.CKK_AES: return "CKK_AES"
    case pkcs11.CKK_BLOWFISH: return "CKK_BLOWFISH"
    case pkcs11.CKK_TWOFISH: return "CKK_TWOFISH"
    case pkcs11.CKK_SECURID: return "CKK_SECURID"
    case pkcs11.CKK_HOTP: return "CKK_HOTP"
    case pkcs11.CKK_ACTI: return "CKK_ACTI"
    case pkcs11.CKK_CAMELLIA: return "CKK_CAMELLIA"
    case pkcs11.CKK_ARIA: return "CKK_ARIA"
    case pkcs11.CKK_MD5_HMAC: return "CKK_MD5_HMAC"
    case pkcs11.CKK_SHA_1_HMAC: return "CKK_SHA_1_HMAC"
    case pkcs11.CKK_RIPEMD128_HMAC: return "CKK_RIPEMD128_HMAC"
    case pkcs11.CKK_RIPEMD160_HMAC: return "CKK_RIPEMD160_HMAC"
    case pkcs11.CKK_SHA256_HMAC: return "CKK_SHA256_HMAC"
    case pkcs11.CKK_SHA384_HMAC: return "CKK_SHA384_HMAC"
    case pkcs11.CKK_SHA512_HMAC: return "CKK_SHA512_HMAC"
    case pkcs11.CKK_SEED: return "CKK_SEED"
    case pkcs11.CKK_GOSTR3410: return "CKK_GOSTR3410"
    case pkcs11.CKK_GOSTR3411: return "CKK_GOSTR3411"
    default: return fmt.Sprintf("CKK_UNKNOWN(0x%08x)", keyType)
    }
}

// getMechanismName maps common CKM_ values to strings (partial list; extend as needed).
func getMechanismName(mech uint32) string {
    switch mech {
    case pkcs11.CKM_RSA_PKCS_KEY_PAIR_GEN: return "CKM_RSA_PKCS_KEY_PAIR_GEN"
    case pkcs11.CKM_RSA_PKCS: return "CKM_RSA_PKCS"
    case pkcs11.CKM_RSA_PKCS_OAEP: return "CKM_RSA_PKCS_OAEP"
    case pkcs11.CKM_AES_KEY_GEN: return "CKM_AES_KEY_GEN"
    case pkcs11.CKM_AES_ECB: return "CKM_AES_ECB"
    case pkcs11.CKM_AES_CBC: return "CKM_AES_CBC"
    case pkcs11.CKM_AES_CBC_PAD: return "CKM_AES_CBC_PAD"
    case pkcs11.CKM_AES_GCM: return "CKM_AES_GCM"
    case pkcs11.CKM_SHA_1: return "CKM_SHA1"
    case pkcs11.CKM_SHA256: return "CKM_SHA256"
    case pkcs11.CKM_ECDSA: return "CKM_ECDSA"
    case pkcs11.CKM_EC_KEY_PAIR_GEN: return "CKM_EC_KEY_PAIR_GEN"
    default: return fmt.Sprintf("CKM_UNKNOWN(0x%08x)", mech)
    }
}


type MechanismEntry struct {
	ID		uint
	Name	string
}

var MechanismMap = map[uint]string {
	pkcs11.CKM_RSA_PKCS_KEY_PAIR_GEN:	"CKM_RSA_PKCS_KEY_PAIR_GEN",
	pkcs11.CKM_RSA_PKCS:	"CKM_RSA_PKCS",
	pkcs11.CKM_RSA_9796:	"CKM_RSA_9796",
	pkcs11.CKM_RSA_X_509:	"CKM_RSA_X_509",
	pkcs11.CKM_MD2_RSA_PKCS:	"CKM_MD2_RSA_PKCS",
	pkcs11.CKM_MD5_RSA_PKCS:	"CKM_MD5_RSA_PKCS",
	pkcs11.CKM_SHA1_RSA_PKCS:	"CKM_SHA1_RSA_PKCS",
	pkcs11.CKM_RIPEMD128_RSA_PKCS:	"CKM_RIPEMD128_RSA_PKCS",
	pkcs11.CKM_RIPEMD160_RSA_PKCS:	"CKM_RIPEMD160_RSA_PKCS",
	pkcs11.CKM_RSA_PKCS_OAEP:	"CKM_RSA_PKCS_OAEP",
	pkcs11.CKM_RSA_X9_31_KEY_PAIR_GEN:	"CKM_RSA_X9_31_KEY_PAIR_GEN",
	pkcs11.CKM_RSA_X9_31:	"CKM_RSA_X9_31",
	pkcs11.CKM_SHA1_RSA_X9_31:	"CKM_SHA1_RSA_X9_31",
	pkcs11.CKM_RSA_PKCS_PSS:	"CKM_RSA_PKCS_PSS",
	pkcs11.CKM_SHA1_RSA_PKCS_PSS:	"CKM_SHA1_RSA_PKCS_PSS",
	pkcs11.CKM_DSA_KEY_PAIR_GEN:	"CKM_DSA_KEY_PAIR_GEN",
	pkcs11.CKM_DSA:	"CKM_DSA",
	pkcs11.CKM_DSA_SHA1:	"CKM_DSA_SHA1",
	pkcs11.CKM_DSA_SHA224:	"CKM_DSA_SHA224",
	pkcs11.CKM_DSA_SHA256:	"CKM_DSA_SHA256",
	pkcs11.CKM_DSA_SHA384:	"CKM_DSA_SHA384",
	pkcs11.CKM_DSA_SHA512:	"CKM_DSA_SHA512",
	pkcs11.CKM_DSA_SHA3_224:	"CKM_DSA_SHA3_224",
	pkcs11.CKM_DSA_SHA3_256:	"CKM_DSA_SHA3_256",
	pkcs11.CKM_DSA_SHA3_384:	"CKM_DSA_SHA3_384",
	pkcs11.CKM_DSA_SHA3_512:	"CKM_DSA_SHA3_512",
	pkcs11.CKM_DH_PKCS_KEY_PAIR_GEN:	"CKM_DH_PKCS_KEY_PAIR_GEN",
	pkcs11.CKM_DH_PKCS_DERIVE:	"CKM_DH_PKCS_DERIVE",
	pkcs11.CKM_X9_42_DH_KEY_PAIR_GEN:	"CKM_X9_42_DH_KEY_PAIR_GEN",
	pkcs11.CKM_X9_42_DH_DERIVE:	"CKM_X9_42_DH_DERIVE",
	pkcs11.CKM_X9_42_DH_HYBRID_DERIVE:	"CKM_X9_42_DH_HYBRID_DERIVE",
	pkcs11.CKM_X9_42_MQV_DERIVE:	"CKM_X9_42_MQV_DERIVE",
	pkcs11.CKM_SHA256_RSA_PKCS:	"CKM_SHA256_RSA_PKCS",
	pkcs11.CKM_SHA384_RSA_PKCS:	"CKM_SHA384_RSA_PKCS",
	pkcs11.CKM_SHA512_RSA_PKCS:	"CKM_SHA512_RSA_PKCS",
	pkcs11.CKM_SHA256_RSA_PKCS_PSS:	"CKM_SHA256_RSA_PKCS_PSS",
	pkcs11.CKM_SHA384_RSA_PKCS_PSS:	"CKM_SHA384_RSA_PKCS_PSS",
	pkcs11.CKM_SHA512_RSA_PKCS_PSS:	"CKM_SHA512_RSA_PKCS_PSS",
	pkcs11.CKM_SHA224_RSA_PKCS:	"CKM_SHA224_RSA_PKCS",
	pkcs11.CKM_SHA224_RSA_PKCS_PSS:	"CKM_SHA224_RSA_PKCS_PSS",
	pkcs11.CKM_SHA512_224:	"CKM_SHA512_224",
	pkcs11.CKM_SHA512_224_HMAC:	"CKM_SHA512_224_HMAC",
	pkcs11.CKM_SHA512_224_HMAC_GENERAL:	"CKM_SHA512_224_HMAC_GENERAL",
	pkcs11.CKM_SHA512_224_KEY_DERIVATION:	"CKM_SHA512_224_KEY_DERIVATION",
	pkcs11.CKM_SHA512_256:	"CKM_SHA512_256",
	pkcs11.CKM_SHA512_256_HMAC:	"CKM_SHA512_256_HMAC",
	pkcs11.CKM_SHA512_256_HMAC_GENERAL:	"CKM_SHA512_256_HMAC_GENERAL",
	pkcs11.CKM_SHA512_256_KEY_DERIVATION:	"CKM_SHA512_256_KEY_DERIVATION",
	pkcs11.CKM_SHA512_T:	"CKM_SHA512_T",
	pkcs11.CKM_SHA512_T_HMAC:	"CKM_SHA512_T_HMAC",
	pkcs11.CKM_SHA512_T_HMAC_GENERAL:	"CKM_SHA512_T_HMAC_GENERAL",
	pkcs11.CKM_SHA512_T_KEY_DERIVATION:	"CKM_SHA512_T_KEY_DERIVATION",
	pkcs11.CKM_SHA3_256_RSA_PKCS:	"CKM_SHA3_256_RSA_PKCS",
	pkcs11.CKM_SHA3_384_RSA_PKCS:	"CKM_SHA3_384_RSA_PKCS",
	pkcs11.CKM_SHA3_512_RSA_PKCS:	"CKM_SHA3_512_RSA_PKCS",
	pkcs11.CKM_SHA3_256_RSA_PKCS_PSS:	"CKM_SHA3_256_RSA_PKCS_PSS",
	pkcs11.CKM_SHA3_384_RSA_PKCS_PSS:	"CKM_SHA3_384_RSA_PKCS_PSS",
	pkcs11.CKM_SHA3_512_RSA_PKCS_PSS:	"CKM_SHA3_512_RSA_PKCS_PSS",
	pkcs11.CKM_SHA3_224_RSA_PKCS:	"CKM_SHA3_224_RSA_PKCS",
	pkcs11.CKM_SHA3_224_RSA_PKCS_PSS:	"CKM_SHA3_224_RSA_PKCS_PSS",
	pkcs11.CKM_RC2_KEY_GEN:	"CKM_RC2_KEY_GEN",
	pkcs11.CKM_RC2_ECB:	"CKM_RC2_ECB",
	pkcs11.CKM_RC2_CBC:	"CKM_RC2_CBC",
	pkcs11.CKM_RC2_MAC:	"CKM_RC2_MAC",
	pkcs11.CKM_RC2_MAC_GENERAL:	"CKM_RC2_MAC_GENERAL",
	pkcs11.CKM_RC2_CBC_PAD:	"CKM_RC2_CBC_PAD",
	pkcs11.CKM_RC4_KEY_GEN:	"CKM_RC4_KEY_GEN",
	pkcs11.CKM_RC4:	"CKM_RC4",
	pkcs11.CKM_DES_KEY_GEN:	"CKM_DES_KEY_GEN",
	pkcs11.CKM_DES_ECB:	"CKM_DES_ECB",
	pkcs11.CKM_DES_CBC:	"CKM_DES_CBC",
	pkcs11.CKM_DES_MAC:	"CKM_DES_MAC",
	pkcs11.CKM_DES_MAC_GENERAL:	"CKM_DES_MAC_GENERAL",
	pkcs11.CKM_DES_CBC_PAD:	"CKM_DES_CBC_PAD",
	pkcs11.CKM_DES2_KEY_GEN:	"CKM_DES2_KEY_GEN",
	pkcs11.CKM_DES3_KEY_GEN:	"CKM_DES3_KEY_GEN",
	pkcs11.CKM_DES3_ECB:	"CKM_DES3_ECB",
	pkcs11.CKM_DES3_CBC:	"CKM_DES3_CBC",
	pkcs11.CKM_DES3_MAC:	"CKM_DES3_MAC",
	pkcs11.CKM_DES3_MAC_GENERAL:	"CKM_DES3_MAC_GENERAL",
	pkcs11.CKM_DES3_CBC_PAD:	"CKM_DES3_CBC_PAD",
	pkcs11.CKM_DES3_CMAC_GENERAL:	"CKM_DES3_CMAC_GENERAL",
	pkcs11.CKM_DES3_CMAC:	"CKM_DES3_CMAC",
	pkcs11.CKM_CDMF_KEY_GEN:	"CKM_CDMF_KEY_GEN",
	pkcs11.CKM_CDMF_ECB:	"CKM_CDMF_ECB",
	pkcs11.CKM_CDMF_CBC:	"CKM_CDMF_CBC",
	pkcs11.CKM_CDMF_MAC:	"CKM_CDMF_MAC",
	pkcs11.CKM_CDMF_MAC_GENERAL:	"CKM_CDMF_MAC_GENERAL",
	pkcs11.CKM_CDMF_CBC_PAD:	"CKM_CDMF_CBC_PAD",
	pkcs11.CKM_DES_OFB64:	"CKM_DES_OFB64",
	pkcs11.CKM_DES_OFB8:	"CKM_DES_OFB8",
	pkcs11.CKM_DES_CFB64:	"CKM_DES_CFB64",
	pkcs11.CKM_DES_CFB8:	"CKM_DES_CFB8",
	pkcs11.CKM_MD2:	"CKM_MD2",
	pkcs11.CKM_MD2_HMAC:	"CKM_MD2_HMAC",
	pkcs11.CKM_MD2_HMAC_GENERAL:	"CKM_MD2_HMAC_GENERAL",
	pkcs11.CKM_MD5:	"CKM_MD5",
	pkcs11.CKM_MD5_HMAC:	"CKM_MD5_HMAC",
	pkcs11.CKM_MD5_HMAC_GENERAL:	"CKM_MD5_HMAC_GENERAL",
	pkcs11.CKM_SHA_1:	"CKM_SHA_1",
	pkcs11.CKM_SHA_1_HMAC:	"CKM_SHA_1_HMAC",
	pkcs11.CKM_SHA_1_HMAC_GENERAL:	"CKM_SHA_1_HMAC_GENERAL",
	pkcs11.CKM_RIPEMD128:	"CKM_RIPEMD128",
	pkcs11.CKM_RIPEMD128_HMAC:	"CKM_RIPEMD128_HMAC",
	pkcs11.CKM_RIPEMD128_HMAC_GENERAL:	"CKM_RIPEMD128_HMAC_GENERAL",
	pkcs11.CKM_RIPEMD160:	"CKM_RIPEMD160",
	pkcs11.CKM_RIPEMD160_HMAC:	"CKM_RIPEMD160_HMAC",
	pkcs11.CKM_RIPEMD160_HMAC_GENERAL:	"CKM_RIPEMD160_HMAC_GENERAL",
	pkcs11.CKM_SHA256:	"CKM_SHA256",
	pkcs11.CKM_SHA256_HMAC:	"CKM_SHA256_HMAC",
	pkcs11.CKM_SHA256_HMAC_GENERAL:	"CKM_SHA256_HMAC_GENERAL",
	pkcs11.CKM_SHA224:	"CKM_SHA224",
	pkcs11.CKM_SHA224_HMAC:	"CKM_SHA224_HMAC",
	pkcs11.CKM_SHA224_HMAC_GENERAL:	"CKM_SHA224_HMAC_GENERAL",
	pkcs11.CKM_SHA384:	"CKM_SHA384",
	pkcs11.CKM_SHA384_HMAC:	"CKM_SHA384_HMAC",
	pkcs11.CKM_SHA384_HMAC_GENERAL:	"CKM_SHA384_HMAC_GENERAL",
	pkcs11.CKM_SHA512:	"CKM_SHA512",
	pkcs11.CKM_SHA512_HMAC:	"CKM_SHA512_HMAC",
	pkcs11.CKM_SHA512_HMAC_GENERAL:	"CKM_SHA512_HMAC_GENERAL",
	pkcs11.CKM_SECURID_KEY_GEN:	"CKM_SECURID_KEY_GEN",
	pkcs11.CKM_SECURID:	"CKM_SECURID",
	pkcs11.CKM_HOTP_KEY_GEN:	"CKM_HOTP_KEY_GEN",
	pkcs11.CKM_HOTP:	"CKM_HOTP",
	pkcs11.CKM_ACTI:	"CKM_ACTI",
	pkcs11.CKM_ACTI_KEY_GEN:	"CKM_ACTI_KEY_GEN",
	pkcs11.CKM_SHA3_256:	"CKM_SHA3_256",
	pkcs11.CKM_SHA3_256_HMAC:	"CKM_SHA3_256_HMAC",
	pkcs11.CKM_SHA3_256_HMAC_GENERAL:	"CKM_SHA3_256_HMAC_GENERAL",
	pkcs11.CKM_SHA3_256_KEY_GEN:	"CKM_SHA3_256_KEY_GEN",
	pkcs11.CKM_SHA3_224:	"CKM_SHA3_224",
	pkcs11.CKM_SHA3_224_HMAC:	"CKM_SHA3_224_HMAC",
	pkcs11.CKM_SHA3_224_HMAC_GENERAL:	"CKM_SHA3_224_HMAC_GENERAL",
	pkcs11.CKM_SHA3_224_KEY_GEN:	"CKM_SHA3_224_KEY_GEN",
	pkcs11.CKM_SHA3_384:	"CKM_SHA3_384",
	pkcs11.CKM_SHA3_384_HMAC:	"CKM_SHA3_384_HMAC",
	pkcs11.CKM_SHA3_384_HMAC_GENERAL:	"CKM_SHA3_384_HMAC_GENERAL",
	pkcs11.CKM_SHA3_384_KEY_GEN:	"CKM_SHA3_384_KEY_GEN",
	pkcs11.CKM_SHA3_512:	"CKM_SHA3_512",
	pkcs11.CKM_SHA3_512_HMAC:	"CKM_SHA3_512_HMAC",
	pkcs11.CKM_SHA3_512_HMAC_GENERAL:	"CKM_SHA3_512_HMAC_GENERAL",
	pkcs11.CKM_SHA3_512_KEY_GEN:	"CKM_SHA3_512_KEY_GEN",
	pkcs11.CKM_CAST_KEY_GEN:	"CKM_CAST_KEY_GEN",
	pkcs11.CKM_CAST_ECB:	"CKM_CAST_ECB",
	pkcs11.CKM_CAST_CBC:	"CKM_CAST_CBC",
	pkcs11.CKM_CAST_MAC:	"CKM_CAST_MAC",
	pkcs11.CKM_CAST_MAC_GENERAL:	"CKM_CAST_MAC_GENERAL",
	pkcs11.CKM_CAST_CBC_PAD:	"CKM_CAST_CBC_PAD",
	pkcs11.CKM_CAST3_KEY_GEN:	"CKM_CAST3_KEY_GEN",
	pkcs11.CKM_CAST3_ECB:	"CKM_CAST3_ECB",
	pkcs11.CKM_CAST3_CBC:	"CKM_CAST3_CBC",
	pkcs11.CKM_CAST3_MAC:	"CKM_CAST3_MAC",
	pkcs11.CKM_CAST3_MAC_GENERAL:	"CKM_CAST3_MAC_GENERAL",
	pkcs11.CKM_CAST3_CBC_PAD:	"CKM_CAST3_CBC_PAD",
	pkcs11.CKM_CAST5_KEY_GEN:	"CKM_CAST5_KEY_GEN",
	pkcs11.CKM_CAST5_ECB:	"CKM_CAST5_ECB",
	pkcs11.CKM_CAST128_CBC:	"CKM_CAST128_CBC",
	pkcs11.CKM_CAST128_MAC:	"CKM_CAST128_MAC",
	pkcs11.CKM_CAST128_MAC_GENERAL:	"CKM_CAST128_MAC_GENERAL",
	pkcs11.CKM_CAST128_CBC_PAD:	"CKM_CAST128_CBC_PAD",
	pkcs11.CKM_RC5_KEY_GEN:	"CKM_RC5_KEY_GEN",
	pkcs11.CKM_RC5_ECB:	"CKM_RC5_ECB",
	pkcs11.CKM_RC5_CBC:	"CKM_RC5_CBC",
	pkcs11.CKM_RC5_MAC:	"CKM_RC5_MAC",
	pkcs11.CKM_RC5_MAC_GENERAL:	"CKM_RC5_MAC_GENERAL",
	pkcs11.CKM_RC5_CBC_PAD:	"CKM_RC5_CBC_PAD",
	pkcs11.CKM_IDEA_KEY_GEN:	"CKM_IDEA_KEY_GEN",
	pkcs11.CKM_IDEA_ECB:	"CKM_IDEA_ECB",
	pkcs11.CKM_IDEA_CBC:	"CKM_IDEA_CBC",
	pkcs11.CKM_IDEA_MAC:	"CKM_IDEA_MAC",
	pkcs11.CKM_IDEA_MAC_GENERAL:	"CKM_IDEA_MAC_GENERAL",
	pkcs11.CKM_IDEA_CBC_PAD:	"CKM_IDEA_CBC_PAD",
	pkcs11.CKM_GENERIC_SECRET_KEY_GEN:	"CKM_GENERIC_SECRET_KEY_GEN",
	pkcs11.CKM_CONCATENATE_BASE_AND_KEY:	"CKM_CONCATENATE_BASE_AND_KEY",
	pkcs11.CKM_CONCATENATE_BASE_AND_DATA:	"CKM_CONCATENATE_BASE_AND_DATA",
	pkcs11.CKM_CONCATENATE_DATA_AND_BASE:	"CKM_CONCATENATE_DATA_AND_BASE",
	pkcs11.CKM_XOR_BASE_AND_DATA:	"CKM_XOR_BASE_AND_DATA",
	pkcs11.CKM_EXTRACT_KEY_FROM_KEY:	"CKM_EXTRACT_KEY_FROM_KEY",
	pkcs11.CKM_SSL3_PRE_MASTER_KEY_GEN:	"CKM_SSL3_PRE_MASTER_KEY_GEN",
	pkcs11.CKM_SSL3_MASTER_KEY_DERIVE:	"CKM_SSL3_MASTER_KEY_DERIVE",
	pkcs11.CKM_SSL3_KEY_AND_MAC_DERIVE:	"CKM_SSL3_KEY_AND_MAC_DERIVE",
	pkcs11.CKM_SSL3_MASTER_KEY_DERIVE_DH:	"CKM_SSL3_MASTER_KEY_DERIVE_DH",
	pkcs11.CKM_TLS_PRE_MASTER_KEY_GEN:	"CKM_TLS_PRE_MASTER_KEY_GEN",
	pkcs11.CKM_TLS_MASTER_KEY_DERIVE:	"CKM_TLS_MASTER_KEY_DERIVE",
	pkcs11.CKM_TLS_KEY_AND_MAC_DERIVE:	"CKM_TLS_KEY_AND_MAC_DERIVE",
	pkcs11.CKM_TLS_MASTER_KEY_DERIVE_DH:	"CKM_TLS_MASTER_KEY_DERIVE_DH",
	pkcs11.CKM_TLS_PRF:	"CKM_TLS_PRF",
	pkcs11.CKM_SSL3_MD5_MAC:	"CKM_SSL3_MD5_MAC",
	pkcs11.CKM_SSL3_SHA1_MAC:	"CKM_SSL3_SHA1_MAC",
	pkcs11.CKM_MD5_KEY_DERIVATION:	"CKM_MD5_KEY_DERIVATION",
	pkcs11.CKM_MD2_KEY_DERIVATION:	"CKM_MD2_KEY_DERIVATION",
	pkcs11.CKM_SHA1_KEY_DERIVATION:	"CKM_SHA1_KEY_DERIVATION",
	pkcs11.CKM_SHA256_KEY_DERIVATION:	"CKM_SHA256_KEY_DERIVATION",
	pkcs11.CKM_SHA384_KEY_DERIVATION:	"CKM_SHA384_KEY_DERIVATION",
	pkcs11.CKM_SHA512_KEY_DERIVATION:	"CKM_SHA512_KEY_DERIVATION",
	pkcs11.CKM_SHA224_KEY_DERIVATION:	"CKM_SHA224_KEY_DERIVATION",
	pkcs11.CKM_SHA3_256_KEY_DERIVE:	"CKM_SHA3_256_KEY_DERIVE",
	pkcs11.CKM_SHA3_224_KEY_DERIVE:	"CKM_SHA3_224_KEY_DERIVE",
	pkcs11.CKM_SHA3_384_KEY_DERIVE:	"CKM_SHA3_384_KEY_DERIVE",
	pkcs11.CKM_SHA3_512_KEY_DERIVE:	"CKM_SHA3_512_KEY_DERIVE",
	pkcs11.CKM_SHAKE_128_KEY_DERIVE:	"CKM_SHAKE_128_KEY_DERIVE",
	pkcs11.CKM_SHAKE_256_KEY_DERIVE:	"CKM_SHAKE_256_KEY_DERIVE",
	pkcs11.CKM_PBE_MD2_DES_CBC:	"CKM_PBE_MD2_DES_CBC",
	pkcs11.CKM_PBE_MD5_DES_CBC:	"CKM_PBE_MD5_DES_CBC",
	pkcs11.CKM_PBE_MD5_CAST_CBC:	"CKM_PBE_MD5_CAST_CBC",
	pkcs11.CKM_PBE_MD5_CAST3_CBC:	"CKM_PBE_MD5_CAST3_CBC",
	pkcs11.CKM_PBE_MD5_CAST128_CBC:	"CKM_PBE_MD5_CAST128_CBC",
	pkcs11.CKM_PBE_SHA1_CAST128_CBC:	"CKM_PBE_SHA1_CAST128_CBC",
	pkcs11.CKM_PBE_SHA1_RC4_128:	"CKM_PBE_SHA1_RC4_128",
	pkcs11.CKM_PBE_SHA1_RC4_40:	"CKM_PBE_SHA1_RC4_40",
	pkcs11.CKM_PBE_SHA1_DES3_EDE_CBC:	"CKM_PBE_SHA1_DES3_EDE_CBC",
	pkcs11.CKM_PBE_SHA1_DES2_EDE_CBC:	"CKM_PBE_SHA1_DES2_EDE_CBC",
	pkcs11.CKM_PBE_SHA1_RC2_128_CBC:	"CKM_PBE_SHA1_RC2_128_CBC",
	pkcs11.CKM_PBE_SHA1_RC2_40_CBC:	"CKM_PBE_SHA1_RC2_40_CBC",
	pkcs11.CKM_PKCS5_PBKD2:	"CKM_PKCS5_PBKD2",
	pkcs11.CKM_PBA_SHA1_WITH_SHA1_HMAC:	"CKM_PBA_SHA1_WITH_SHA1_HMAC",
	pkcs11.CKM_WTLS_PRE_MASTER_KEY_GEN:	"CKM_WTLS_PRE_MASTER_KEY_GEN",
	pkcs11.CKM_WTLS_MASTER_KEY_DERIVE:	"CKM_WTLS_MASTER_KEY_DERIVE",
	pkcs11.CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC:	"CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC",
	pkcs11.CKM_WTLS_PRF:	"CKM_WTLS_PRF",
	pkcs11.CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE:	"CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE",
	pkcs11.CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE:	"CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE",
	pkcs11.CKM_TLS10_MAC_SERVER:	"CKM_TLS10_MAC_SERVER",
	pkcs11.CKM_TLS10_MAC_CLIENT:	"CKM_TLS10_MAC_CLIENT",
	pkcs11.CKM_TLS12_MAC:	"CKM_TLS12_MAC",
	pkcs11.CKM_TLS12_KDF:	"CKM_TLS12_KDF",
	pkcs11.CKM_TLS12_MASTER_KEY_DERIVE:	"CKM_TLS12_MASTER_KEY_DERIVE",
	pkcs11.CKM_TLS12_KEY_AND_MAC_DERIVE:	"CKM_TLS12_KEY_AND_MAC_DERIVE",
	pkcs11.CKM_TLS12_MASTER_KEY_DERIVE_DH:	"CKM_TLS12_MASTER_KEY_DERIVE_DH",
	pkcs11.CKM_TLS12_KEY_SAFE_DERIVE:	"CKM_TLS12_KEY_SAFE_DERIVE",
	pkcs11.CKM_TLS_MAC:	"CKM_TLS_MAC",
	pkcs11.CKM_TLS_KDF:	"CKM_TLS_KDF",
	pkcs11.CKM_KEY_WRAP_LYNKS:	"CKM_KEY_WRAP_LYNKS",
	pkcs11.CKM_KEY_WRAP_SET_OAEP:	"CKM_KEY_WRAP_SET_OAEP",
	pkcs11.CKM_CMS_SIG:	"CKM_CMS_SIG",
	pkcs11.CKM_KIP_DERIVE:	"CKM_KIP_DERIVE",
	pkcs11.CKM_KIP_WRAP:	"CKM_KIP_WRAP",
	pkcs11.CKM_KIP_MAC:	"CKM_KIP_MAC",
	pkcs11.CKM_CAMELLIA_KEY_GEN:	"CKM_CAMELLIA_KEY_GEN",
	pkcs11.CKM_CAMELLIA_ECB:	"CKM_CAMELLIA_ECB",
	pkcs11.CKM_CAMELLIA_CBC:	"CKM_CAMELLIA_CBC",
	pkcs11.CKM_CAMELLIA_MAC:	"CKM_CAMELLIA_MAC",
	pkcs11.CKM_CAMELLIA_MAC_GENERAL:	"CKM_CAMELLIA_MAC_GENERAL",
	pkcs11.CKM_CAMELLIA_CBC_PAD:	"CKM_CAMELLIA_CBC_PAD",
	pkcs11.CKM_CAMELLIA_ECB_ENCRYPT_DATA:	"CKM_CAMELLIA_ECB_ENCRYPT_DATA",
	pkcs11.CKM_CAMELLIA_CBC_ENCRYPT_DATA:	"CKM_CAMELLIA_CBC_ENCRYPT_DATA",
	pkcs11.CKM_CAMELLIA_CTR:	"CKM_CAMELLIA_CTR",
	pkcs11.CKM_ARIA_KEY_GEN:	"CKM_ARIA_KEY_GEN",
	pkcs11.CKM_ARIA_ECB:	"CKM_ARIA_ECB",
	pkcs11.CKM_ARIA_CBC:	"CKM_ARIA_CBC",
	pkcs11.CKM_ARIA_MAC:	"CKM_ARIA_MAC",
	pkcs11.CKM_ARIA_MAC_GENERAL:	"CKM_ARIA_MAC_GENERAL",
	pkcs11.CKM_ARIA_CBC_PAD:	"CKM_ARIA_CBC_PAD",
	pkcs11.CKM_ARIA_ECB_ENCRYPT_DATA:	"CKM_ARIA_ECB_ENCRYPT_DATA",
	pkcs11.CKM_ARIA_CBC_ENCRYPT_DATA:	"CKM_ARIA_CBC_ENCRYPT_DATA",
	pkcs11.CKM_SEED_KEY_GEN:	"CKM_SEED_KEY_GEN",
	pkcs11.CKM_SEED_ECB:	"CKM_SEED_ECB",
	pkcs11.CKM_SEED_CBC:	"CKM_SEED_CBC",
	pkcs11.CKM_SEED_MAC:	"CKM_SEED_MAC",
	pkcs11.CKM_SEED_MAC_GENERAL:	"CKM_SEED_MAC_GENERAL",
	pkcs11.CKM_SEED_CBC_PAD:	"CKM_SEED_CBC_PAD",
	pkcs11.CKM_SEED_ECB_ENCRYPT_DATA:	"CKM_SEED_ECB_ENCRYPT_DATA",
	pkcs11.CKM_SEED_CBC_ENCRYPT_DATA:	"CKM_SEED_CBC_ENCRYPT_DATA",
	pkcs11.CKM_SKIPJACK_KEY_GEN:	"CKM_SKIPJACK_KEY_GEN",
	pkcs11.CKM_SKIPJACK_ECB64:	"CKM_SKIPJACK_ECB64",
	pkcs11.CKM_SKIPJACK_CBC64:	"CKM_SKIPJACK_CBC64",
	pkcs11.CKM_SKIPJACK_OFB64:	"CKM_SKIPJACK_OFB64",
	pkcs11.CKM_SKIPJACK_CFB64:	"CKM_SKIPJACK_CFB64",
	pkcs11.CKM_SKIPJACK_CFB32:	"CKM_SKIPJACK_CFB32",
	pkcs11.CKM_SKIPJACK_CFB16:	"CKM_SKIPJACK_CFB16",
	pkcs11.CKM_SKIPJACK_CFB8:	"CKM_SKIPJACK_CFB8",
	pkcs11.CKM_SKIPJACK_WRAP:	"CKM_SKIPJACK_WRAP",
	pkcs11.CKM_SKIPJACK_PRIVATE_WRAP:	"CKM_SKIPJACK_PRIVATE_WRAP",
	pkcs11.CKM_SKIPJACK_RELAYX:	"CKM_SKIPJACK_RELAYX",
	pkcs11.CKM_KEA_KEY_PAIR_GEN:	"CKM_KEA_KEY_PAIR_GEN",
	pkcs11.CKM_KEA_KEY_DERIVE:	"CKM_KEA_KEY_DERIVE",
	pkcs11.CKM_KEA_DERIVE:	"CKM_KEA_DERIVE",
	pkcs11.CKM_FORTEZZA_TIMESTAMP:	"CKM_FORTEZZA_TIMESTAMP",
	pkcs11.CKM_BATON_KEY_GEN:	"CKM_BATON_KEY_GEN",
	pkcs11.CKM_BATON_ECB128:	"CKM_BATON_ECB128",
	pkcs11.CKM_BATON_ECB96:	"CKM_BATON_ECB96",
	pkcs11.CKM_BATON_CBC128:	"CKM_BATON_CBC128",
	pkcs11.CKM_BATON_COUNTER:	"CKM_BATON_COUNTER",
	pkcs11.CKM_BATON_SHUFFLE:	"CKM_BATON_SHUFFLE",
	pkcs11.CKM_BATON_WRAP:	"CKM_BATON_WRAP",
	pkcs11.CKM_EC_KEY_PAIR_GEN:	"CKM_EC_KEY_PAIR_GEN",
	pkcs11.CKM_ECDSA:	"CKM_ECDSA",
	pkcs11.CKM_ECDSA_SHA1:	"CKM_ECDSA_SHA1",
	pkcs11.CKM_ECDSA_SHA224:	"CKM_ECDSA_SHA224",
	pkcs11.CKM_ECDSA_SHA256:	"CKM_ECDSA_SHA256",
	pkcs11.CKM_ECDSA_SHA384:	"CKM_ECDSA_SHA384",
	pkcs11.CKM_ECDSA_SHA512:	"CKM_ECDSA_SHA512",
	pkcs11.CKM_ECDH1_DERIVE:	"CKM_ECDH1_DERIVE",
	pkcs11.CKM_ECDH1_COFACTOR_DERIVE:	"CKM_ECDH1_COFACTOR_DERIVE",
	pkcs11.CKM_ECMQV_DERIVE:	"CKM_ECMQV_DERIVE",
	pkcs11.CKM_ECDH_AES_KEY_WRAP:	"CKM_ECDH_AES_KEY_WRAP",
	pkcs11.CKM_RSA_AES_KEY_WRAP:	"CKM_RSA_AES_KEY_WRAP",
	pkcs11.CKM_JUNIPER_KEY_GEN:	"CKM_JUNIPER_KEY_GEN",
	pkcs11.CKM_JUNIPER_ECB128:	"CKM_JUNIPER_ECB128",
	pkcs11.CKM_JUNIPER_CBC128:	"CKM_JUNIPER_CBC128",
	pkcs11.CKM_JUNIPER_COUNTER:	"CKM_JUNIPER_COUNTER",
	pkcs11.CKM_JUNIPER_SHUFFLE:	"CKM_JUNIPER_SHUFFLE",
	pkcs11.CKM_JUNIPER_WRAP:	"CKM_JUNIPER_WRAP",
	pkcs11.CKM_FASTHASH:	"CKM_FASTHASH",
	pkcs11.CKM_AES_KEY_GEN:	"CKM_AES_KEY_GEN",
	pkcs11.CKM_AES_ECB:	"CKM_AES_ECB",
	pkcs11.CKM_AES_CBC:	"CKM_AES_CBC",
	pkcs11.CKM_AES_MAC:	"CKM_AES_MAC",
	pkcs11.CKM_AES_MAC_GENERAL:	"CKM_AES_MAC_GENERAL",
	pkcs11.CKM_AES_CBC_PAD:	"CKM_AES_CBC_PAD",
	pkcs11.CKM_AES_CTR:	"CKM_AES_CTR",
	pkcs11.CKM_AES_GCM:	"CKM_AES_GCM",
	pkcs11.CKM_AES_CCM:	"CKM_AES_CCM",
	pkcs11.CKM_AES_CTS:	"CKM_AES_CTS",
	pkcs11.CKM_AES_CMAC:	"CKM_AES_CMAC",
	pkcs11.CKM_AES_CMAC_GENERAL:	"CKM_AES_CMAC_GENERAL",
	pkcs11.CKM_AES_XCBC_MAC:	"CKM_AES_XCBC_MAC",
	pkcs11.CKM_AES_XCBC_MAC_96:	"CKM_AES_XCBC_MAC_96",
	pkcs11.CKM_AES_GMAC:	"CKM_AES_GMAC",
	pkcs11.CKM_BLOWFISH_KEY_GEN:	"CKM_BLOWFISH_KEY_GEN",
	pkcs11.CKM_BLOWFISH_CBC:	"CKM_BLOWFISH_CBC",
	pkcs11.CKM_TWOFISH_KEY_GEN:	"CKM_TWOFISH_KEY_GEN",
	pkcs11.CKM_TWOFISH_CBC:	"CKM_TWOFISH_CBC",
	pkcs11.CKM_BLOWFISH_CBC_PAD:	"CKM_BLOWFISH_CBC_PAD",
	pkcs11.CKM_TWOFISH_CBC_PAD:	"CKM_TWOFISH_CBC_PAD",
	pkcs11.CKM_DES_ECB_ENCRYPT_DATA:	"CKM_DES_ECB_ENCRYPT_DATA",
	pkcs11.CKM_DES_CBC_ENCRYPT_DATA:	"CKM_DES_CBC_ENCRYPT_DATA",
	pkcs11.CKM_DES3_ECB_ENCRYPT_DATA:	"CKM_DES3_ECB_ENCRYPT_DATA",
	pkcs11.CKM_DES3_CBC_ENCRYPT_DATA:	"CKM_DES3_CBC_ENCRYPT_DATA",
	pkcs11.CKM_AES_ECB_ENCRYPT_DATA:	"CKM_AES_ECB_ENCRYPT_DATA",
	pkcs11.CKM_AES_CBC_ENCRYPT_DATA:	"CKM_AES_CBC_ENCRYPT_DATA",
	pkcs11.CKM_GOSTR3410_KEY_PAIR_GEN:	"CKM_GOSTR3410_KEY_PAIR_GEN",
	pkcs11.CKM_GOSTR3410:	"CKM_GOSTR3410",
	pkcs11.CKM_GOSTR3410_WITH_GOSTR3411:	"CKM_GOSTR3410_WITH_GOSTR3411",
	pkcs11.CKM_GOSTR3410_KEY_WRAP:	"CKM_GOSTR3410_KEY_WRAP",
	pkcs11.CKM_GOSTR3410_DERIVE:	"CKM_GOSTR3410_DERIVE",
	pkcs11.CKM_GOSTR3411:	"CKM_GOSTR3411",
	pkcs11.CKM_GOSTR3411_HMAC:	"CKM_GOSTR3411_HMAC",
	pkcs11.CKM_GOST28147_KEY_GEN:	"CKM_GOST28147_KEY_GEN",
	pkcs11.CKM_GOST28147_ECB:	"CKM_GOST28147_ECB",
	pkcs11.CKM_GOST28147:	"CKM_GOST28147",
	pkcs11.CKM_GOST28147_MAC:	"CKM_GOST28147_MAC",
	pkcs11.CKM_GOST28147_KEY_WRAP:	"CKM_GOST28147_KEY_WRAP",
	pkcs11.CKM_DSA_PARAMETER_GEN:	"CKM_DSA_PARAMETER_GEN",
	pkcs11.CKM_DH_PKCS_PARAMETER_GEN:	"CKM_DH_PKCS_PARAMETER_GEN",
	pkcs11.CKM_X9_42_DH_PARAMETER_GEN:	"CKM_X9_42_DH_PARAMETER_GEN",
	pkcs11.CKM_DSA_PROBABLISTIC_PARAMETER_GEN:	"CKM_DSA_PROBABLISTIC_PARAMETER_GEN",
	pkcs11.CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN:	"CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN",
	pkcs11.CKM_AES_OFB:	"CKM_AES_OFB",
	pkcs11.CKM_AES_CFB64:	"CKM_AES_CFB64",
	pkcs11.CKM_AES_CFB8:	"CKM_AES_CFB8",
	pkcs11.CKM_AES_CFB128:	"CKM_AES_CFB128",
	pkcs11.CKM_AES_CFB1:	"CKM_AES_CFB1",
	pkcs11.CKM_AES_KEY_WRAP:	"CKM_AES_KEY_WRAP",
	pkcs11.CKM_AES_KEY_WRAP_PAD:	"CKM_AES_KEY_WRAP_PAD",
	pkcs11.CKM_RSA_PKCS_TPM_1_1:	"CKM_RSA_PKCS_TPM_1_1",
	pkcs11.CKM_RSA_PKCS_OAEP_TPM_1_1:	"CKM_RSA_PKCS_OAEP_TPM_1_1",
}
